name: Build and Push Docker Image
inputs:
  docker-username:
    required: true
  docker-password:
    required: true
  docker-tag:
    required: true

runs:
  using: "composite"
  steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PAT }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags:
          - ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }}
          - ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ inputs.docker-tag }}
